name: CI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - name: Install dependancies
              run: yarn install --frozen-lockfile

            - name: Build Next.js
              run: yarn build

            - name: Run tests
              run: yarn test
